# Generated by Django 6.1.1 on 2026-09-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moment',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
