# Generated by Django 6.1.1 on 2026-10-04 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], default='hard', max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=2)),
                ('description', models.TextField(blank=True)),
                ('starred_by', models.ManyToManyField(blank=True, related_name='starred_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
