# Generated by Django 6.1.1 on 2026-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
